# Generated by Django 5.2.17 on 2026-10-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emaillog_status_suppressed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("suppressed", "Suppressed"),
                    ("rate_limited", "Rate limited"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
