# Generated by Django 5.2.17 on 2026-10-02 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_alter_tenantsettings_used_tiers_for_offers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="sepa_collection_day_of_month",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Default day of month on which the bank should execute SEPA direct-debit collections. The billing-run form pre-fills the collection date with this day of the chosen month (today, if that day has passed); the office can change it. Nothing moves it for SEPA lead times or TARGET banking days.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
    ]
