# Generated by Django 5.2.17 on 2026-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_alter_tenantsettings_sepa_collection_day_of_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="require_admin_approval_for_gdpr_deletion",
            field=models.BooleanField(
                default=True,
                help_text="Has no effect: every deletion request needs an office/admin approval after the email-confirm step, whatever this says.",
            ),
        ),
    ]
