# Generated by Django 5.2.17 on 2026-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_gdpr_deletion_gate_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="info_sentence_about_coop_shares",
            field=models.TextField(blank=True, null=True),
        ),
    ]
