# Generated by Django 5.2.17 on 2026-10-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0030_date_transfer_exits_by_the_latest_transfer"),
        ("gdpr", "0003_mask_audit_log_values_in_full"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deletionlog",
            name="member_pk",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="deletionlog",
            name="reseller_pk",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="deletionlog",
            name="user_pk",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="deletionrequest",
            name="channel",
            field=models.CharField(
                choices=[
                    ("self_service", "Self-service"),
                    ("email", "Email"),
                    ("letter", "Letter"),
                    ("phone", "Phone"),
                    ("in_person", "In person"),
                ],
                default="self_service",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deletionrequest",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="commissioning.member",
            ),
        ),
        migrations.AddField(
            model_name="deletionrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deletionrequest",
            name="reseller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="commissioning.reseller",
            ),
        ),
        migrations.AlterField(
            model_name="deletionlog",
            name="user_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the user whose data was deleted (for audit trail). Empty for a subject without an email address.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="deletionrequest",
            name="requested_email",
            field=models.EmailField(
                blank=True,
                help_text="Email at the moment the request was made — captured so the audit trail survives the anonymization itself.",
                max_length=254,
            ),
        ),
    ]
