# Generated by Django 5.2.17 on 2026-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdpr", "0004_deletion_subject_keys_and_office_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletionrequest",
            name="requires_admin_approval",
            field=models.BooleanField(
                default=True,
                help_text="Whether an office/admin must approve after the email-confirm step. True on every new request; older rows keep the value they were created with.",
            ),
        ),
    ]
