# Generated by Django 5.2.17 on 2026-10-05 12:26

from django.db import migrations, models


def stored_light_to_system(apps, schema_editor):
    # No screen and no API could set ``theme`` until this release, so every
    # ``light`` is the old default rather than a choice: those users follow
    # their device like new ones do.
    JasminUser = apps.get_model("accounts", "JasminUser")
    JasminUser.objects.filter(theme="light").update(theme="system")


def system_to_light(apps, schema_editor):
    JasminUser = apps.get_model("accounts", "JasminUser")
    JasminUser.objects.filter(theme="system").update(theme="light")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_audit_log_user_labels_without_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jasminuser",
            name="theme",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                max_length=10,
            ),
        ),
        migrations.RunPython(stored_light_to_system, system_to_light),
    ]
